package Junit;
import methods.Money;	

import junit.framework.TestCase;


public class MoneyTest extends TestCase {

	private Money m12chf;
	private Money m14chf;
	
	public MoneyTest(String name) {
		super(name);
	}

	protected void setUp() throws Exception {
		m12chf= new Money(12,"CHF");
		m14chf= new Money(14,"CHF");
	}

	
		
	
	public void testAdd() {
		Money expected= new Money(26,"CHF");
		Money result = null;
		try {
		result= (Money)m12chf.add(m14chf);
		} catch (Exception e) {
			 // If an exception is caught, print the error message and pass the test
	        System.out.println("Exception caught: " + e.getMessage());
	        assertTrue(true);
	        return;
		}
		assertTrue(expected.equals(result));
		
	}
